# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtailsharing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareableRoutablePageModel',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailsharing.models.ShareableRoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
